version: '3.4'

services:
  database_ui:
    image: adminer:4-standalone

  php:
    volumes:
      - ${DIRECTORY}/api:/srv/api:rw,cached

  api:
    volumes:
      - ${DIRECTORY}/api/public:/srv/api/public:ro
