version: '3.4'

services:
  php:
    volumes:
      - ${DIRECTORY}/api/config/jwt/key:/srv/api/config/jwt/key:rw
      - ${DIRECTORY}/api/config/jwt/key.pub:/srv/api/config/jwt/key.pub:rw
      - ${DIRECTORY}/api/var/cache:/srv/api/var/cache:rw
      - ${DIRECTORY}/api/var/logs:/srv/api/var/logs:rw
