version: '3.4'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    image: digitalstate/microservice/php
    build:
      context: ./api
      target: api_platform_php
    depends_on:
      - database
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  api:
    image: digitalstate/microservice/nginx
    build:
      context: ./api
      target: api_platform_nginx
    depends_on:
      - php

volumes:
  database_data: {}
