parameters:
  env(VARNISH_URL): ''

api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  title: Microservice
  version: 0.15.0
  http_cache:
    invalidation:
      enabled: true
      varnish_urls: ['%env(VARNISH_URL)%']
    max_age: 0
    shared_max_age: 3600
    vary: ['Content-Type', 'Authorization']
    public: true
