parameters:
  env(APP): ''
  env(DISCOVERY_HOST): ''
  env(DISCOVERY_CREDENTIAL): ''
  env(ENCRYPTION): ''

ds_discovery:
  host: '%env(resolve:DISCOVERY_HOST)%'
  credential: '%env(resolve:DISCOVERY_CREDENTIAL)%'

ds_encryption:
  encryption: '%env(resolve:ENCRYPTION)%'

ds_entity:
  uuidentifiable: true

ds_log:
  app: '%env(resolve:APP)%'
