framework:
  secret: '%env(APP_SECRET)%'
  #default_locale: en
  #csrf_protection: ~
  #http_method_override: true
  session:
    handler_id: ~
  #esi: ~
  #fragments: ~
  php_errors:
    log: true
  cache:
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost
