security:
  providers:
    in_memory:
      memory: ~
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern:   ^/
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
